### ISSUE TITLE
setuptools-odoo broken with setuptools >= 31.0.0 for Odoo 10

### ISSUE THREAD

**Issue by sbidoul** [acsone/setuptools-odoo#10] opened 2016-12-31 10:20 UTC
This affects Odoo 10.

Symptom is

```console
$ odoo
Traceback (most recent call last):
  File "/home/sbi-local/.virtualenvs/odoo-10c/bin/odoo", line 17, in <module>
    odoo.cli.main()
AttributeError: 'module' object has no attribute 'cli'
```

This is apparently due to the `*-nspkg.pth` files creating a dummy `odoo` package before the python program starts, therefore making `import odoo` do nothing and preventing `odoo/__init__.py` from being properly executed.

Until a workaround is found, stick to "setuptools<31" to build wheels.

**Comment by sbidoul** [comment] 2017-01-01 20:13
Wheels on wheelhouse.odoo-community.org/oca are unaffected so far.

**Comment by sbidoul** [comment] 2017-01-03 11:45
A possible workaround: https://github.com/acsone/odoo/commit/a5b490c4e9bb017dcf951e9ecb5cba22b486b4ad

**Comment by adrienpeiffer** [comment] 2017-01-03 16:19
acsone/odoo@a5b490c works for me

**Comment by eLBati** [comment] 2017-03-03 15:01
Patch works for me too.
Shouldn't this be fixed in odoo itself?
Is there an open issue or PR already?
Thanks

**Comment by sbidoul** [comment] 2017-03-05 15:28
@eLBati I just submitted https://github.com/odoo/odoo/pull/15718

**Comment by sbidoul** [comment] 2017-09-15 17:13
As a better alternative to odoo/odoo#15718 I implemented an automatic patching mechanism ion odoo-autodiscover: https://github.com/acsone/odoo-autodiscover/pull/3.

If you want to test with Odoo 10, just `pip install git+https://github.com/acsone/odoo-autodiscover@autopatch-sbi`. After that `from odoo import cli, api` should work just fine.

Feedback welcome.

**Closed** 2017-09-17 15:59 UTC
Labels: bug

**Comment by sbidoul** [comment] 2017-09-17 16:53
odoo-autodiscover 2.0.0b1 is on pypi. People impacted by this issue can test if `pip install "odoo-autodiscover >=2.0.0b1"` resolves the issue.

**Comment by eLBati** [comment] 2018-05-20 14:40
@sbidoul Hi,

after having installed ```odoo-autodiscover==2.0.0```, I successfully installed an OCA module (```odoo11-addon-date-range```) without getting the error.

If I build my custom module with ```setuptools-odoo-make-default -d .``` and ```python setup.py bdist_wheel``` and install it, I get
```
Traceback (most recent call last):
  File "bin/odoo", line 8, in <module>
    odoo.cli.main()
AttributeError: module 'odoo' has no attribute 'cli'
```
Do you build OCA modules differently?

Thanks

**Comment by sbidoul** [comment] 2018-05-20 15:40
Hi @eLBati,

That should work. 

Can you provide a bit more details? eg result of `pip list`? How exactly do you install and launch Odoo?

**Comment by eLBati** [comment] 2018-05-21 07:16
Hi @sbidoul after checking all involved packages, it seems I did not update ```wheel```
Thanks

**Comment by JonathanNEMRY** [comment] 2018-08-30 14:07
Hello @sbidoul  
I face the same error but into a different context: is it possible that this bug appears again with odoo11 and python3.0? After having installed from a wheel's directory everythings seems well installed (pip list seems OK) but when I try to launch "odoo" I have this same error:
``AttributeError: module 'odoo' has no attribute 'cli'
``
Do you have any idea ?

many thanks

**Comment by sbidoul** [comment] 2018-08-30 14:26
Hi Jonathan! AFAIK this problem does not occur on v11 with python 3. By chance would you have some remaining `__init__.py` in odoo or odoo/addons directories? They must all be removed (except in odoo itself).

**Comment by JonathanNEMRY** [comment] 2018-08-30 15:11
Actually I already fixed this point.
But One important thing is that my project works well in local, all installed is fine, but when I build the wheels and try to install from them then my odoo is not runable with this error. So my conclusion is that something is wrong from 
* the way I install from the wheels ...small chance
* the whells are not well build as it should be 

Hope you can see what am I doing wrong with those informations

thanks again

**Comment by sbidoul** [comment] 2018-08-30 15:15
> Hope you can see what am I doing wrong with those informations

Unfortunately not. Look in sys.path everywhere you have and `odoo` directory. Only one of them must have a `__init__.py` (odoo's of course).

**Comment by JonathanNEMRY** [comment] 2018-08-30 21:01
OK so I cleaned all my project restarting into new environements defining a quick-step to reproduce the error:
* quick create an odoo python project with `mrbob acsoo:templates/project` (with recent fix about the python3 compatibility)
* cd new project and mkvirtualenv --python=python3_path project_env
* then install the project with pip install -r requirement-dev after what you can generated the requirements.txt
* now run odoo command: it perfectly works
* launch acsoo wheel --> release is well created with all its required packages (tested with fresh setuptools and also with a old version like 28.0
* no create into an other directory a simple python3 venv 
* go into it and launch pip install --no-deps --no-index your_project/release/*.whl
--> everything will be ok: your pip list, your installation but when trying to launch `odoo` command then it crash by saying there is no attribute cli to the odoo package :disappointed:

**Comment by JonathanNEMRY** [comment] 2018-08-30 21:43
@sbidoul when you say ` Only one of them must have a __init__.py (odoo's of course).` --> it is true when generating the wheels but at the end, after installing them, the init of the odoo is not the same anymore...is is only a declaration of package instead of the real init file of Odoo...replacing it by the original allow us to launch the odoo application :open_mouth:

**Comment by sufyanel** [comment] 2018-09-05 07:05
I'm facing exactly the same issue as @JonathanNEMRY

**Comment by sbidoul** [comment] 2018-09-05 07:45
Can you provide a minimal project (setup.py, etc) with a detailed procedure to reproduce?
