### ISSUE TITLE
Import of Odoo fails if Odoo installed with `pip install -e`

### ISSUE THREAD

**Issue by codingforfun** [acsone/setuptools-odoo#18] opened 2017-09-12 09:23 UTC
This is a bit special problem but maybe also relevant for your project. 
I tried to integrate your approach of installing Odoo addons via pip into the [docker-odoo-project](https://github.com/camptocamp/docker-odoo-project) from camptocamp. 

The following problems arise: Odoo is installed from source via `pip install -e`. After this modules are installed via a `requirements.txt` file in the project. Modules requiring Odoo as a dependency (like all modules from `https://wheelhouse.odoo-community.org/`) somehow break `import odoo` statements in following scripts. 

I don't really understand the problem, but I was able to temporarily solve this by manually removing the corresponding `nspkg.pth` files from dist-packages. I assume it has to do with `namespace_packages: ['odoo', 'odoo.addons']` in setup.py. 

I reported the problem here: https://github.com/camptocamp/docker-odoo-project/issues/38

A minimal example can be found here: https://github.com/codingforfun/test-odoo-project/tree/pip-issue

I think integrating the docker approach with the approach of installing Odoo modules from PIP would be really a great thing, so any pointer you have to solve the problem would be very appreciated since I'm unfortunately not that firm with python packaging details.

**Comment by sbidoul** [comment] 2017-09-12 10:39
I think you are being hit by https://github.com/acsone/setuptools-odoo/issues/10

Could you try either
- pip install "setuptools<31" (before any installation with -e)
- or https://github.com/odoo/odoo/pull/15718

Let me know how it works.

I'm currently thinking about a more robust solution for v11 that would not involve namespace packages.

**Comment by codingforfun** [comment] 2017-09-12 11:19
I did a quick test with your [patch](https://github.com/odoo/odoo/commit/00d9c63f7f3461868b0d91640ceb5d22c7b2e047). Unfourtunately this didn't change anything. 

To test your other proposal takes a bit more time, since I have to modifiy the parent container for this. I will try this next asap.

**Comment by sbidoul** [comment] 2017-09-12 11:53
Hm, this `import openerp as odoo` I see in the stack trace is something I never tested.

**Comment by codingforfun** [comment] 2017-09-12 13:25
Note: This is a bit misleading. The core problem is, that `import odoo` fails. The attempt to `import openerp as odoo` is just a fallback for older odoo versions and has nothing to do with the problem itself. It's just symptom. 
So the core problem is that odoo isn't installed properly / can't get imported although installed.

Here you can see what I mean: https://github.com/camptocamp/anthem/blob/master/anthem/cli.py#L17

**Comment by sbidoul** [comment] 2017-09-12 14:03
I understand. This is annoying. So the only possibility I see is `setuptools<31` or apply something similar to https://github.com/odoo/odoo/pull/15718 to any program that does `import odoo`.

Note that merely doing `pip install odoo10-addon...` should not cause issues because all such packages on pypi and wheelhouse.odoo-community.org are buillt with `setuptools<31`.

**Comment by codingforfun** [comment] 2017-09-12 20:50
I tried your suggestion and it seams to work. I pinned setuptools to 30.4.0 in the requirements file of the parent container, but unfortunately it didn't help.

**Comment by sbidoul** [comment] 2017-09-12 20:51
I'm experimenting an alternative solution.

**Comment by sbidoul** [comment] 2017-09-12 21:29
@codingforfun could you try running the following command after installing odoo and before running any program that does `import odoo`?

`pip install git+https://github.com/acsone/odoo-autodiscover@autopatch-sbi`

Then run your programs normally. Don't worry about the scripts in odoo-autodiscover (they are not needed and are for odoo < 10 anyway).

In this branch I attempt a trick to apply https://github.com/odoo/odoo/pull/15718 transparently.

**Comment by codingforfun** [comment] 2017-09-13 08:57
@sbidoul 
I can try this in the evening. 
I have another idea. Do you think the problem could also be the [setup.py](https://github.com/codingforfun/test-odoo-project/blob/master/odoo/setup.py) in the project?
I took this over from camptocamp. The idea is to install the whole project as a package itself. After reading through packaging of namespace packages guide [here](https://packaging.python.org/guides/packaging-namespace-packages/) I am wondering if I rather should install all the migration code for my project as a subpackage of odoo to solve the problem.

**Comment by codingforfun** [comment] 2017-09-13 11:23
@sbidoul 
Your suggested solution is working. Thanks a lot. 
Can you help me to understand this better? I still don't got the problem completely. 

What I think I got is:
+ Odoo needs to run some extra code from it's `__init__.py` to function properly.
+ In the current case odoo is just a dummy package and therefor `__init__.py` isn't run. 
  + Why is this? Is this due to using namespace packages or due to installing Odoo via the `-e` option? 

Do you think it makes sense to isolate your hack with the `post_import_hook` into a separate helper library?

**Comment by codingforfun** [comment] 2017-09-14 07:21
Note to myself: This are the necessary changes: https://github.com/acsone/odoo-autodiscover/compare/autopatch-sbi

**Comment by sbidoul** [comment] 2017-09-14 08:01
@codingforfun this package is `odoo-autodiscover`. I'll do a new release soon.

**Comment by sbidoul** [comment] 2017-09-14 08:03
The rest of `odoo-autodiscover` is for 8 and 9 but that's fine to have everything in the same package.

**Comment by sbidoul** [comment] 2017-09-15 17:10
@codingforfun I've updated the odoo-autodiscover autopatch branch. I intend to push a release candidate to pypi over the weekend.

**Comment by codingforfun** [comment] 2017-09-15 19:29
@sbidoul This is great. Thanks a lot. I've worked with your current branch and had no problems so far.

**Comment by sbidoul** [comment] 2017-09-17 15:31
Closing as duplicate of #10

**Closed by sbidoul** 2017-09-17 15:31 UTC
Labels: bug

**Comment by codingforfun** [comment] 2017-09-18 14:27
@sbidoul I've seen you made the release. Thanks. Short question anyways: 
Shouldn't there be an explicit version statement in [setup.py](https://github.com/acsone/odoo-autodiscover/blob/7ec7cb5a6c083792fd46d42e33f6b2a02149cc75/setup.py#L11) instead of `use_scm_version=True`? At least this was what you did for older releases.

**Comment by sbidoul** [comment] 2017-09-18 14:38
That's the [magic of setuptools-scm](https://github.com/pypa/setuptools_scm) which computes the version automatically from the last git tag. So, with [a little help from travis](https://github.com/acsone/odoo-autodiscover/blob/7ec7cb5a6c083792fd46d42e33f6b2a02149cc75/.travis.yml#L13-L25), [making a release](https://github.com/acsone/odoo-autodiscover/blob/master/DEVELOP.rst#how-to-release) boils down to `git tag && git push --tags`

**Comment by oussamaben18** [comment] 2024-01-12 10:00
hy everyone, please can someone help me with the requirements in odoo 9 i did them but i heve pillow problem and python-ldap

**Comment by sbidoul** [comment] 2024-01-12 10:12
@oussamaben18 sorry, this is not related to this project. This question is best asked on a generic Odoo support forum such as https://www.odoo.com/forum/help-1.
